### ISSUE TITLE
Preserve Helm dependency options

### ISSUE THREAD

**Issue by cehoffman** [app-registry/appr#67]
It would be nice for an appr dependency in a helm `requirements.yaml` to pass through other helm dependency options than just `name`, `version`, and `repository`. A use case is the dependency option `condition` which allows a dependency to be enabled depending on a value in user supplied configuration.

For example:

```yaml
appr:
- name: reg.my.company/org/chart
  version: 0.1.0
  condition: subdep.enabled
```

would result in 

```yaml
dependencies:
- name: chart
  version: 0.1.0
  repository: file://appr_charts/org/chart
  condition: subdep.enabled
appr:
- name: reg.my.company/org/chart
  version: 0.1.0
  condition: subdep.enabled
```
